### ISSUE TITLE
defaultdict

### ISSUE THREAD

**Issue by kuzmichevdima** [ftvkyo2011-study/python-review1#1]
https://github.com/ftvkyo2011-study/python-review1/blob/e288c3aa97175ed06819966e58c9cb00372fe0a8/markov/model.py#L23-L29

чтобы не нужны были эти проверки, используй defaultdict

**Comment by ftvkyo2011** [comment]
Сделано.
https://github.com/ftvkyo2011-study/python-review1/blob/66d045ac92b582890643394b8b61806392abe080/markov/model.py#L13-L15
https://github.com/ftvkyo2011-study/python-review1/blob/66d045ac92b582890643394b8b61806392abe080/markov/model.py#L41
66d045ac92b582890643394b8b61806392abe080
