### ISSUE TITLE
взвешенный выбор

### ISSUE THREAD

**Issue by kuzmichevdima** [ftvkyo2011-study/python-review1#2]
https://github.com/ftvkyo2011-study/python-review1/blob/e288c3aa97175ed06819966e58c9cb00372fe0a8/markov/model.py#L32-L33

**Comment by ftvkyo2011** [comment]
Сделано.
https://github.com/ftvkyo2011-study/python-review1/blob/66d045ac92b582890643394b8b61806392abe080/markov/model.py#L43-L53
66d045ac92b582890643394b8b61806392abe080
