### ISSUE TITLE
отделить "приватные" методы

### ISSUE THREAD

**Issue by kuzmichevdima** [ftvkyo2011-study/python-review1#5]
https://github.com/ftvkyo2011-study/python-review1/blob/e288c3aa97175ed06819966e58c9cb00372fe0a8/markov/model.py#L19-L29

можно двумя подчеркиваниями __add_connection

**Comment by ftvkyo2011** [comment]
Вроде все "приватное" теперь является приватным.
66d045ac92b582890643394b8b61806392abe080
