### ISSUE TITLE
вывод по 1 слову

### ISSUE THREAD

**Issue by kuzmichevdima** [ftvkyo2011-study/python-review1#7]
https://github.com/ftvkyo2011-study/python-review1/blob/31c285386e1f7f59f2027c6ae74ff1d324fe1990/generate.py#L20-L21

Во-первых, это медленно. Во-вторых, так получается 1 длинная строка, а не текст

**Comment by ftvkyo2011** [comment]
4dc16808f2237207bec0bbfbe81476bbd5c6348d
Конкретно: https://github.com/ftvkyo2011-study/python-review1/blob/4dc16808f2237207bec0bbfbe81476bbd5c6348d/markov/io.py#L52

**Comment by kuzmichevdima** [comment]
https://github.com/ftvkyo2011-study/python-review1/blob/4dc16808f2237207bec0bbfbe81476bbd5c6348d/markov/io.py#L65
это просто супердолго, а главное зачем?
придумай, как выводить короткие строки без того, чтоб видеть все слова (words). Обработка каждого нового слова должна быть быстрой

**Comment by ftvkyo2011** [comment]
Не подумал. Забыл, что строчки каждый раз создаются заново при каждом изменении, потому что они иммутабельны.
Хорошо, подумаю.

**Comment by ftvkyo2011** [comment]
Теперь `generate.py` принимает на вход аргумент `--block`, который по умолчанию равен `10`. Он отвечает за количество слов, которые программа выводит за раз.
