### ISSUE TITLE
сокращение

### ISSUE THREAD

**Issue by kuzmichevdima** [ftvkyo2011-study/python-review1#8]
https://github.com/ftvkyo2011-study/python-review1/blob/31c285386e1f7f59f2027c6ae74ff1d324fe1990/markov/model.py#L39-L41

это можно сделать в 1 строку без создания 3 переменных

**Comment by ftvkyo2011** [comment]
4dc16808f2237207bec0bbfbe81476bbd5c6348d
https://github.com/ftvkyo2011-study/python-review1/blob/4dc16808f2237207bec0bbfbe81476bbd5c6348d/markov/model.py#L43
