### ISSUE TITLE
названия

### ISSUE THREAD

**Issue by kuzmichevdima** [ftvkyo2011-study/python-review1#9]
Почти всегда однобуквенные названия не оправданы

https://github.com/ftvkyo2011-study/python-review1/blob/31c285386e1f7f59f2027c6ae74ff1d324fe1990/markov/model.py#L65

https://github.com/ftvkyo2011-study/python-review1/blob/31c285386e1f7f59f2027c6ae74ff1d324fe1990/markov/model.py#L79

**Comment by ftvkyo2011** [comment]
4dc16808f2237207bec0bbfbe81476bbd5c6348d
https://github.com/ftvkyo2011-study/python-review1/blob/4dc16808f2237207bec0bbfbe81476bbd5c6348d/markov/model.py#L67-L82

**Comment by kuzmichevdima** [comment]
https://github.com/ftvkyo2011-study/python-review1/blob/4dc16808f2237207bec0bbfbe81476bbd5c6348d/markov/model.py#L85

это же "приватный" метод, почему нет _?

**Comment by kuzmichevdima** [comment]
https://github.com/ftvkyo2011-study/python-review1/blob/4dc16808f2237207bec0bbfbe81476bbd5c6348d/markov/io.py#L36
то же самое

**Comment by ftvkyo2011** [comment]
prepare_symbols используется в https://github.com/ftvkyo2011-study/python-review1/blob/4dc16808f2237207bec0bbfbe81476bbd5c6348d/markov/model.py#L70
другое пофиксил
